/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '3/20/16 10:46 PM' with Gradle 2.10
 *
 * @author ltudor, @date 3/20/16 10:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
